### ISSUE TITLE
UserProfileSerializer doesn't handle foreignKey fields?

### ISSUE THREAD

**Issue by jonas87** [apragacz/django-rest-registration#106]
So I have a foreignKey on one of the fields of my User model (did this by subclassing AbstractUser and pointing AUTH_USER_MODEL in settings.py to this User model). These extra fields are showing up correctly in my calls to "accounts/register/". However when I'm submitting my registration form I'm submitting an integer that represents the primary key for this foreignKey field and I get the following error:
Cannot assign "4": "User.user_type" must be a "UserType" instance.

The error happens in _build_initial_user() on line 175 of [rest_registration/api/serializers.py](https://github.com/apragacz/django-rest-registration/blob/master/rest_registration/api/serializers.py) because it's trying to construct an instance of the usermodel there with self.initial_data which holds an integer for the ForeignKey field.

**Comment by apragacz** [comment]
Hi @jonas87 
Just to let you know on the current situation: I'm currently working on a test which will reproduce the issue. Unfortunately I have to do some refactors so I can start write tests the new pytesty way. I hope I will be able to do that till tomorrow.

After that, we could work on the MR you provided (so we can be sure that it indeed fixes the issue by having a reproduced example in the test).

**Comment by apragacz** [comment]
@jonas87 I dropped the test in `master`, it is currently skipped (as it fails). Let's continue the discussion in PR #107.
