### ISSUE TITLE
How can I change 'REGISTER_VERIFICATION_EMAIL_TEMPLATES' files addresses?!

### ISSUE THREAD

**Issue by hrahmadi71** [apragacz/django-rest-registration#115]
I installed django-rest-registration using pip, so it's located in virtual environment and I want to alter verification email body and subject template in my project. but any address I'm trying, ends up with this error message:
```console
SystemCheckError: System check identified some issues:

ERRORS:
?: (rest_registration.E007) REGISTER_VERIFICATION_EMAIL_TEMPLATES is invalid

System check identified 1 issue (0 silenced).
```
For example I've tried this config and I get the above error:
```python
REST_REGISTRATION = {
    'RESET_PASSWORD_VERIFICATION_ENABLED': False,
    'REGISTER_SERIALIZER_PASSWORD_CONFIRM': False,
    'REGISTER_VERIFICATION_PERIOD': datetime.timedelta(days=3),

    # this is where I get the error:
    'REGISTER_VERIFICATION_EMAIL_TEMPLATES': {'body': 'my_project/mail_templates/register/body.txt',
                                              'subject': 'my_project/mail_templates/register/subject.txt'},

    'REGISTER_VERIFICATION_URL': config.RestRegistration.REGISTER_VERIFICATION_URL,
    'REGISTER_EMAIL_VERIFICATION_URL': config.RestRegistration.REGISTER_EMAIL_VERIFICATION_URL,
    'USER_VERIFICATION_ID_FIELD': 'username',
    'VERIFICATION_FROM_EMAIL': DEFAULT_FROM_EMAIL,
}
```
I've read the documentation but there was not any point about how should I address `body.txt` and `subject.txt` files?

**Comment by hrahmadi71** [comment]
My bad! I found the right way to do that! You can delete this issue. :)

**Comment by apragacz** [comment]
@hrahmadi71 

> My bad! I found the right way to do that! 

I appreciate that you found what was the problem. You're more than welcome to share how you did it!

My wild guess that was because the template paths could not be resolved - could be something with your template backends setup.

Anyway, for the posterity - you can debug it by running your `python manage.py shell`

and then use the following lines:

```python
from rest_registration.notifications.email import parse_template_config
from rest_registration.settings import registration_settings
parse_template_config(registration_settings.REGISTER_VERIFICATION_EMAIL_TEMPLATES)
```

If everything is alright you should get `EmailTemplateConfig` object, if not you will get `ImproperlyConfigured` exception with appropriate message.

> You can delete this issue. :)

Actually, I'm thankful that you reported it. It means that the system check message does not convey enough information. I will create a separate issue to improve this one.

**Comment by hrahmadi71** [comment]
Yes, it was the template paths. I found out that I should address the templates from `templates` folder! Cause templates was configured like this:
```python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # <-- path of templates root directory.
    # ... 
    },
]
```
So `REGISTER_VERIFICATION_EMAIL_TEMPLATES` config, was looking for paths from this directory.

Accordingly I put `body.txt` and `subject.txt` file into `my_project/templates/register` folder and I changed its config in `settings.py` file to this:
```python
REST_REGISTRATION = {
    # ...
    'REGISTER_VERIFICATION_EMAIL_TEMPLATES': {'body': 'register/body.txt',
                                              'subject': 'register/subject.txt'},
    # ...
}
```
