### ISSUE TITLE
When will the next version be released?

### ISSUE THREAD

**Issue by BeWe11** [apragacz/django-rest-registration#128]
Hey,

The latest version 0.5.6 has been released in April 2020. Since then, a lot of important fixes have been commited. In particular, the commit https://github.com/apragacz/django-rest-registration/commit/f9e8fcc3461cac62d2ed131945bca3c5276b0a07 fixes an issue that breaks user registration when the email address and/or username are not editable.

Is there a planned timeframe for the next release?

Thank your for this library!

**Comment by apragacz** [comment]
Hi @BeWe11 ,
The next version will be released when milestone [Version 0.6](https://github.com/apragacz/django-rest-registration/milestone/1) will be finished. I can't give you specific date but given my limited time and the existing progress in the milestone (the last issue is in progress right now) it should be within this month, optimistically by end of the upcoming week.

Unfortunately releasing minor version `0.5.7` would be hard now considering the fact that some minor changes are mixed up with major ones.

**Comment by BeWe11** [comment]
Hey @apragacz,

thank you for your answer. I'm looking forward to version 0.6 :)

**Comment by apragacz** [comment]
@BeWe11 FYI new version has been released few days ago. Hope that helps!

**Comment by BeWe11** [comment]
Thank your for the quick release, @apragacz!
