### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by liveashish** [apragacz/django-rest-registration#129]
Even though I'm trying to login with valid Login and Password, still I'm getting an error "Login or password invalid.

Using the latest release of django-rest-registration

**Comment by apragacz** [comment]
Hi @liveashish,
thanks for reporting this issue.

Unfortunately I need more information to be able to reproduce the actual problem.

Please use the ["Bug report" issue template](https://github.com/apragacz/django-rest-registration/issues/new?assignees=&labels=type%3Abug&template=bug_report.md&title=) and provide necessary information.

You may add more info there, like the Django and DRF versions (this is not in the template, I should probably update it)

**Comment by liveashish** [comment]
I am using Django==3.1 and djangorestframework==3.12.1

I am trying to implement a custom serializer for both registration and login

```
class UserSerializer(serializers.ModelSerializer):
    workspace = serializers.SerializerMethodField()
    fullName = serializers.CharField(source='full_name')
    
    class Meta:
        model = User
        fields = ('id', 'email', 'fullName', 'workspace', 'password')
        extra_kwargs = {'password': {'write_only': True}}
        
    def create(self, validated_data):
            password = validated_data.pop('password')
            user = User(**validated_data)
            user.set_password(password)
            user.save()
            workspace_obj = Workspace.objects.create(name=namegenerator.gen())
            SiteIntegration.objects.create(workspace=workspace_obj)
            WorkspaceMember.objects.create(
                workspace=workspace_obj, member=user
            )
            return user

```

My settings goes below:

```
REST_REGISTRATION = {
    'REGISTER_VERIFICATION_ENABLED': True,
    'REGISTER_EMAIL_VERIFICATION_ENABLED': False,
    'RESET_PASSWORD_VERIFICATION_ENABLED': False,
    'REGISTER_VERIFICATION_AUTO_LOGIN': True,
    'REGISTER_SERIALIZER_PASSWORD_CONFIRM': False,
    'REGISTER_SERIALIZER_CLASS': 'accounts.serializers.UserSerializer',
    'REGISTER_VERIFICATION_ONE_TIME_USE': True,
    
    'REGISTER_VERIFICATION_URL': 'http://localhost:8888/verify-user/',
    'RESET_PASSWORD_VERIFICATION_URL': 'https://frontend-host/reset-password/',
    'REGISTER_EMAIL_VERIFICATION_URL': 'https://frontend-host/verify-email/',
    
    'VERIFICATION_FROM_EMAIL': 'no-reply@example.com',
    
}

```

Installed Apps:

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_registration',
    'rest_registration',
    'drf_yasg',
    'cloudinary_storage',
    'cloudinary',
    'accounts',
]
```

API Response:

```
{
    "detail": "Login or password invalid."
}
```

**Comment by apragacz** [comment]
Thanks @liveashish, that gives me more insight. I have following questions:

1. What part of user data are you using as 'Login' when doing a login? Is it the user email or something else?
1. Could you share your user model class code as well?
2. Or more specifically, did you set up [USERNAME_FIELD](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD) field in your user model? I don't see [REST_REGISTRATION['USER_LOGIN_FIELDS']](https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/user.html#user-login-fields) being set and in that case `USERNAME_FIELD` will be used to identify which fields should be regarded as the "login" ones. Looking at your custom serializer my guess is that `USERNAME_FIELD` should be set to `'email'` (I don't see any other username-like fields listed there). If it's not set that could explain the issue.
