### ISSUE TITLE
Template path builder

### ISSUE THREAD

**Issue by quertenmont** [apragacz/django-rest-registration#133]
Hello,

It would be nice to have the  REGISTER_VERIFICATION_EMAIL_TEMPLATES and RESET_PASSWORD_VERIFICATION_EMAIL_TEMPLATES settings to accept a function
or alternatively to have a settings to build the template path on the fly.

My use case, is that I have the same backend accepting users of different sorts and the invitation email that I want to send them differs according to their profile and other extra parameters.

Now, I have to rewrite the entire "send_invite" viewset while I only need to change the template actually.

thanks in advance for considering this proposal,
All the best,
Loic

**Comment by apragacz** [comment]
Hi @quertenmont 

Generally, this should be handled by the template(s) itself - you could make it conditional and have specific sections of the template(s) for given user type.

But if you think it's really annoying and would prefer to have these templates separated I think we could add something like  `VERIFICATION_TEMPLATES_BUILDER` function, which would give you the power to do that (by default it would only choose between `*_EMAIL_TEMPLATES` depending on the type of notification.

My only question is what this function should take as parameters? 
My pick is:
* `user`
* `notification_type`
* `notification_method` (currently only email)

Optionally:
* `request` - but I'm unsure here

If the function would be unable to find the matching templates, custom `VerificationTemplatesNotFound` exception - in that case we could try to fall back to the default templates selection.

You mentioned "and other extra parameters"... what exactly you had in mind?

**Comment by quertenmont** [comment]
@apragacz that would be awesome.

Having the request as an argument to the function would give me access to the "extra parameters" I need.
(typically the referrer url)

Thanks for the support.
Loic

**Comment by apragacz** [comment]
Hi @quertenmont,
I created PR #139 with the proposed solution. let me know if you any comments. If not, I will merge it in ~7 days.
