### ISSUE TITLE
deprecated get_user_or_none

### ISSUE THREAD

**Issue by rj76** [apragacz/django-rest-registration#138]
### Checklist

*   [ x ] I read [Contribution Guidelines](https://github.com/apragacz/django-rest-registration/blob/master/CONTRIBUTING.md#issues)
*   [ x ] I searched [the documentation](https://django-rest-registration.readthedocs.io/) to ensure that the requested feature is not already implemented and described
*   [ x ] I searched existing issues before opening this one

### Is your feature request related to a problem? Please describe.
This warning is being shown, yet the documentation does not offer an alternative. It still says you have to implement `get_user_or_none`.

SEND_RESET_PASSWORD_LINK_SERIALIZER_CLASS contains deprecated get_user_or_none method, which will be removed in version 0.7.0

### Describe the solution you'd like

I would like to know how to migrate in the future.

**Comment by apragacz** [comment]
Hi @rj76,
The documentation describes an alternative, but it looks that the warning is not pointing to it in an intuitive way.
In short, you need to use `SEND_RESET_PASSWORD_LINK_USER_FINDER`: 
https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/all_settings.html#send-reset-password-link-user-finder

I will add a note to the deprecation warning to make it more clear.
Hope that helps.

**Comment by apragacz** [comment]
Hi @rj76, I hope my comment helped; if not, please let me know.
The deprecation warning will be updated in the next version (`0.6.2`).
