### ISSUE TITLE
Login with email not working.

### ISSUE THREAD

**Issue by psk007** [apragacz/django-rest-registration#141]
Hello,
I set 'USER_LOGIN_FIELDS': ['username','email'](email is unique), so it should be possible to login with email, but it is not possible and login view return 400 error code with the message: login or password is invalid. 
Is there any extra configuration for login with email?

**Comment by apragacz** [comment]
Hi @psk007 ,
thanks for the heads-up.

I was able to reproduce the issue with a test case and produce a fix (see 356c036350e94638c84b582fdd1f38d24cdc8f33).

If it is possible, please verify that it works with the current master. I plan to release this change soon (version `0.6.3`).
