### ISSUE TITLE
Cannot install dev dependencies

### ISSUE THREAD

**Issue by Neraste** [apragacz/django-rest-registration#143]
### Describe the bug

Running `make install_dev` with Python 3.8 crashes, preventing to install dev dependencies.

### Expected behavior

Dependencies installed.

### Actual behavior

Crashes with:

```log
ERROR: Cannot install -r requirements/requirements-dev.lock.txt (line 164) and ipython==7.16.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested ipython==7.16.1
    ipdb 0.13.7 depends on ipython>=7.17.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

### Steps to reproduce

```sh
git clone git@github.com:apragacz/django-rest-registration.git
cd django-rest-registration
# create virtual environment
git checkout 0.6.2  # optional
make install_dev
```

**Comment by apragacz** [comment]
@Neraste thanks for the heads-up! Not sure why that one happened.

I updated the requirements on `master` and they should install without conflict; please check again.

If there is still a problem, you may use `make install_test` as the stuff installed by `make install_dev` is not essential for development.

**Comment by Neraste** [comment]
OK, it works, thanks.
