### ISSUE TITLE
It's possible to add nested models to the user profile view?

### ISSUE THREAD

**Issue by dbalboa** [apragacz/django-rest-registration#149]
I have the following table to extend the User model:

`class UserProfile(models.Model):`
`user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='profile', on_delete=models.CASCADE)`
`phone_number = models.CharField(max_length=50, null=True)`
`...`

I've tested overriding the `User` model and adding one field and it worked fine, but I think is cleaner to extend the user data with another table as it have more fields. I think overriding the user adding fields there would dirt the default `User` class a lot, although there is no consensus in the searches I've done about what's the best option.

Still, I would find useful to be able to query and change the nested model related to the user, with some kind of settings like these:

`'USER_PUBLIC_FIELDS': ['username', 'first_name', 'profile__phone_number'],`
`'USER_EDITABLE_FIELDS': ['username', 'first_name', 'last_name', 'profile__phone_number'],`

**Comment by apragacz** [comment]
Hi @dbalboa ,
currently there is no plan to support that unless more people request it. My recommendation would be to to use custom user model (when you start a new django project), either derived from `AbstractBaseUser` or `AbstractUser` (if you prefer the "dirt", as you said it):
https://docs.djangoproject.com/en/dev/topics/auth/customizing/#substituting-a-custom-user-model

The advantages of that is:
* You control the whole model. If at some point your business requirements change, you can get rid of specific fields
* All the data is in one place (model) you avoid cohesive data dislocation
* Additionally, you avoid unneeded table join at the SQL level.

The disadvantage is that you need to learn a little bit of Django User API, but it's a small cost compared to the advantages IMO.

**Comment by dbalboa** [comment]
Guess I'll go with what you propose. When searching the pros/const about extending the user model with a related table or replacing it derived from AbstractUser, saw some comments saying that the User model should have only the auth information so its better organised, although those stackoverflow questions were a bit old.

Still, as you said, if more people are interested in this feature it may be interesting to investigate.

**Comment by apragacz** [comment]
Closing this issue (I assume, by the lack of activity, that main questions were answered)
