### ISSUE TITLE
Add ‘REGISTER_RETRIEVE_TOKEN’

### ISSUE THREAD

**Issue by trentmercer** [apragacz/django-rest-registration#159]
### Checklist

*   [x] I read [Contribution Guidelines](https://github.com/apragacz/django-rest-registration/blob/master/CONTRIBUTING.md#issues)
*   [x] I searched [the documentation](https://django-rest-registration.readthedocs.io/) to ensure that the requested feature is not already implemented and described
*   [x] I searched existing issues before opening this one

There should be an option so successful user registration returns an auth token, similar to how login works.

**Comment by apragacz** [comment]
There was similar issue some time ago. You should be able to implement that feature if you follow the instructions in the comment below:

https://github.com/apragacz/django-rest-registration/issues/31#issuecomment-443329792

I will still think whether this should be added as an option, but it may be hard to do with one switch as two serializers need to be modified.

**Comment by apragacz** [comment]
@trentmercer let me know if you have any further comments.
