### ISSUE TITLE
Support for Django 4.x

### ISSUE THREAD

**Issue by one4many** [apragacz/django-rest-registration#172]
1) Since Django 3.1 _providing_args_ in the Signal dispatcher has been marked deprecated:
https://github.com/jazzband/django-simple-history/issues/723

It has been removed in 4.x with no replacement and 0.6.5 is considered incompatible/broken with Django 4.x

Just remove the argument _providing_args_ or convert it to a documentation string.

2) Since Django 3.1 urls from 'from django.conf.urls import url' has been marked deprecated and has been removed in Django 4.x.

Please use re_path in order to be compatible again.

**Comment by apragacz** [comment]
Hi @one4many,
thanks for raising this.
I was aware of the deprecation, but I missed the Django 4.0 release :)
I hope to release the fix till the end of this year (probably as version `0.7.0`).

**Comment by apragacz** [comment]
Support for Django 4.x was released via `0.7.0` version. Hope it works as expected.
