### ISSUE TITLE
Setting to disable new user registration (the `/register` endpoint)

### ISSUE THREAD

**Issue by 1ace** [apragacz/django-rest-registration#186]
### Checklist

*   [x] I read [Contribution Guidelines](https://github.com/apragacz/django-rest-registration/blob/master/CONTRIBUTING.md#issues)
*   [x] I searched [the documentation](https://django-rest-registration.readthedocs.io/) to ensure that the requested feature is not already implemented and described
*   [x] I searched existing issues before opening this one

### Is your feature request related to a problem? Please describe.
Sometimes, we need to stop new users from registering, while still continuing to provide the rest of the functionalities from this library to existing users.

### Describe the solution you'd like
I would like to be able to disable registration of new users (the `/register` endpoint) based on a [setting](https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/all_settings.html).

### Describe alternatives you've considered
Reading through the list of existing settings (and reading the code to make sure there isn't an undocumented setting), there doesn't seem to be any :upside_down_face:
The best I can come up with (but haven't had time to test yet) is to define a custom [`REGISTER_SERIALIZER_CLASS`](https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/all_settings.html#register-serializer-class) that would be a copy of [the one already provided](https://github.com/apragacz/django-rest-registration/blob/master/rest_registration/api/serializers.py#L96) with an added exception at the beginning of `validate()`, thrown based on a django setting.

**Comment by apragacz** [comment]
Hi @1ace,
thanks for the very detailed description.

Another alternative would be just to include a subset of Django REST Registration urls instead of including the whole `rest_registration.api.urls` config, but I understand this is a cumbersome thing to do.

On the other hand, adding a simple boolean setting (i.e. `REGISTER_FLOW_ENABLED`) should not be too costly, so I think I will go with that approach.

**Comment by apragacz** [comment]
Added `REGISTER_FLOW_ENABLED` setting, change will be released in next version (0.7.2).

**Comment by 1ace** [comment]
Awesome, thank you!

Do you have an idea when you'll make a new release?  Just so I know whether I should start using `master`, or if I can just wait a few days and have a shiny new release :sparkles:

**Comment by 1ace** [comment]
That was really quick!  Thanks for everything @apragacz :pray:
