### ISSUE TITLE
Page not found (404)

### ISSUE THREAD

**Issue by onurbyrl** [apragacz/django-rest-registration#187]
![image](https://user-images.githubusercontent.com/67410757/160584998-679e9dc0-3898-4a98-baf6-e7b0b702be2a.png)

<p>what should I do now?</p>

**Comment by onurbyrl** [comment]
<h2>These are codes in urls.py</h2>


from django.urls import path, include

api_urlpatterns = [
    path('accounts/', include('rest_registration.api.urls')),
]

urlpatterns = [
    path('api/v1/', include(api_urlpatterns)),
]

// I also did things that I have to do in settings.py

**Comment by apragacz** [comment]
Hi @onurbyrl 
this is to be expected - in that case `http:/localhost:8000/api/v1/accounts` is not valid REST endpoint, but for instance http:/localhost:8000/api/v1/accounts/register/ should work as expected.

**Comment by apragacz** [comment]
Let me know if there are any further questions. For any general Django questions I'd advise to check the official Django docs: https://docs.djangoproject.com/ or DRF docs: https://www.django-rest-framework.org/

**Comment by onurbyrl** [comment]
I already tried url that you mentioned. But I got the error below:

![image](https://user-images.githubusercontent.com/67410757/160649793-a49383bc-ace7-415b-9048-046b0d7c6452.png)

**Comment by onurbyrl** [comment]
I apologize, I should create my templates and views first, then try it again.

**Comment by apragacz** [comment]
I'm closing that one, as it seems to be unrelated to Django REST Registration. Please create a new issue if it is specific to this project.

Again, for Django-specific questions I recommend to ask a question on Forum/IRC channel listed here: https://www.djangoproject.com/community/ or ask on StackOverflow.
