### ISSUE TITLE
Remove check for LOGIN_FIELDS being unique

### ISSUE THREAD

**Issue by simon-ccoms** [apragacz/django-rest-registration#208]
In my setup, I make the User's email non-unique (deliberately) as I have multiple sites under the same API and the same email address should be able to be used on more than one site.

In my authentication methods for logging these users on, I check that the login data also contains a reference to the site they're trying to log on to so that the combination of "site and email address" *is* unique. But email itself is not unique.

But as it stands, this library won't let me do that because of the check that all the LOGIN_FIELDS (one of which is email) are unique.

**Comment by apragacz** [comment]
Hi @simon-ccoms, sorry for lack of response. I added 'USER_LOGIN_FIELDS_UNIQUE_CHECK_ENABLED' setting  which gives you the ability do disable that check.

It will be released in the next version (`v0.8.3`).
