### ISSUE TITLE
Returning profile serializer on registration. Change to return own registration serializer. 

### ISSUE THREAD

**Issue by polinom** [apragacz/django-rest-registration#21]
It seems to me that, returning profile serializer after registration is not appropriate. 
I think registration should have it's own serializer to return data. 

For example when user registers I'm creating a bunch of staff in profile that user should not know about before it activates account and logs in, but now he will receive all that back when first time hitting my registration endpoint, and there is no way to reconfigure it, because I do need profile serializer in  a way it implemented now.  

I would expect this behavior more after `login` than `register`. 

https://github.com/szopu/django-rest-registration/blob/51ddffa91507efbf63a57f71de5c42bf65e04c1b/rest_registration/api/views/register.py#L35-L70

**Comment by apragacz** [comment]
I added `REGISTER_OUTPUT_SERIALIZER_CLASS` which allows you to replace the serializer with something different than the profile serializer, which is still the default. I will consider replacing the default profile serializer there to register serializer in future versions (`0.4.*`).
