### ISSUE TITLE
Enabling an option to send html emails

### ISSUE THREAD

**Issue by PotatoDrug** [apragacz/django-rest-registration#22]
The current `send_verification` function only allows sending of plain text emails, would be nice to have and option in the settings to send html emails.

I believe sending of html emails can be done by `email_msg.content_subtype = 'html'`
https://github.com/apragacz/django-rest-registration/blob/0c1f599924c0134502cb048fec3cee23c381016c/rest_registration/notifications/email.py#L8-L29

**Comment by apragacz** [comment]
Interesting idea, I will try to tackle it this weekend.

**Comment by apragacz** [comment]
HTML emails are still undocumented, but you can see valid cases of configuration here:
https://github.com/apragacz/django-rest-registration/blob/22fb5472dfd389fef3ddc159d2304ea4c442203e/rest_registration/notifications/email.py#L80-L133

There are unit-tests but to be sincere I didn't see how such sent e-mail looks in a real mail reader.
