### ISSUE TITLE
Minor suggestion: correct typo in reset password view name

### ISSUE THREAD

**Issue by oriyalperin** [apragacz/django-rest-registration#268]
I have noticed a minor naming inconsistency while testing my project. The issue is related to the view associated with the reset password, named '[ResetPassordView](https://github.com/apragacz/django-rest-registration/blob/8a21bbaf31f46949168760adfbc9d5f201f72c07/rest_registration/api/views/reset_password.py#L79C7-L79C23)'.

Screenshot: 
![image](https://github.com/apragacz/django-rest-registration/assets/73301483/1d47da24-4f5f-471b-93f0-c30b2782eaec)

While this is a very minor issue, it caught my attention. The inconsistency is in the name of the view - the misspelled 'Passord' instead of 'Password'. I'm not sure if there are any significant consequences to this name change, but it's worth addressing for consistency and clarity.

I'd be willing to help and contribute to resolve this issue if the maintainers find it necessary.

Thanks for maintaining this package! :)

**Comment by apragacz** [comment]
Hi @oriyalperin

It looks it was a typo 🤦 ; thanks for pointing that out.

I fixed that typo, the change will be released in next version (v.0.8.3).
