### ISSUE TITLE
Failed to load http://127.0.0.1:8000/a/login/: Request header field Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers in preflight response.

### ISSUE THREAD

**Issue by lamrhari07** [apragacz/django-rest-registration#27]
I followed the basic steps  and things were fine until I tried to connect my backend API with ReactJs and this error showed off saying that "Access-Control-Allow-Origin is not allowed by Access-Control-Allow-Headers"

App.js

`axios({method:'post',url: 'http://127.0.0.1:8000/a/login/',headers: {
      'Access-Control-Allow-Origin': '*',
        }})
      .then(res => {
        const user = res.data;
        this.setState({ user });
        console.log(res.data)
      })`

settings.py

`CORS_ORIGIN_ALLOW_ALL = True`

But, when I change the URL into a different url of mine things works perfect with GET

**Comment by apragacz** [comment]
As far as I know one does not specify the CORS headers when doing request from frontend, but the CORS headers are returned in the response from the backend when performing any HTTP request (`GET`, `OPTIONS`...) as an information for the browser whether the same-origin policy should be enforced or not. You can refer to the docs here:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Also, there is a blog post about CORS I stumbled upon recently:
https://frontendian.co/cors

I'm assuming that you are using [django-cors-headers](https://github.com/ottoyiu/django-cors-headers) in your project and you configured it correctly (I see only one line from `settings.py`, so I'm guessing). In this case, please remove the `headers: ` part from the axios call and check whether the problem occurs again. If there are other problems with CORS, my guess is that django-cors-headers is improperly configured. If you have problems with configuring django-cors-headers you can look at the sharedlinks example:
https://github.com/apragacz/django-rest-registration/tree/master/examples/sharedlinks/

**Comment by apragacz** [comment]
@lamrhari07 Did my response help in any way?

**Comment by lamrhari07** [comment]
@apragacz I did what you said, I cleaned up all the header and I got 400 Bad request error as a result, and then I realized that my code is fine. To avoid this you need a username and password to access since they are required. My solution; axios.post(`http://127.0.0.1:8000/account/login/`,{username:'Username', password:'password}) For fetch you would add this: JSON.stringify({ username:'....', password:'...' })  
            .then(res => {. Thank yuu.
