### ISSUE TITLE
Customized registration process

### ISSUE THREAD

**Issue by oriyalperin** [apragacz/django-rest-registration#276]
Hi,
I have a model called `student` in my project, which includes a `user` field.
During the registration process, I aim to create both the student and user objects.
What would be the recommended approach for adding the student creation step to the user registration?

Thanks

**Comment by apragacz** [comment]
Hi @oriyalperin ,
I don't have all the details; in the simple case, a way to solve this would be to create a subclass of `rest_registration.api.serializers.DefaultRegisterUserSerializer` and override the `create` method there. This method should:
1. call super version of `create(..)` to create the user
2. create the student model instance with the created user
3. return the user (not the student)

then, that class should be set via `"REGISTER_SERIALIZER_CLASS"` key in `REST_REGISTRATION` setting: https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/register.html#register-serializer-class
You may also need to adjust `"REGISTER_OUTPUT_SERIALIZER_CLASS"` accordingly.

This is in case you can derive all data required to create a student object from the auto-generated fields from the user. In other case,  you may need to override `get_fields` method to add more fields for the student data.

In case you require more complex input/output (e.g student JSON with nested user dict), you may need to write your serializers from scratch and I can't help you much here 🤷 . The DRR requirement for that (input) serializer would be that `create` method should return user instance.

**Comment by apragacz** [comment]
@oriyalperin  let me know if you have any more questions.

**Comment by oriyalperin** [comment]
@apragacz thanks a lot for your detailed response! I'll implement your suggestions and let you know if anything comes up.

**Comment by oriyalperin** [comment]
It works, thank you!
How do I handle registration form errors, especially with the student fields?
I want to send a response with the right error message.

**Comment by apragacz** [comment]
@oriyalperin 
> How do I handle registration form errors, especially with the student fields?

DRR does not use forms (I assume you're talking about backend only, as DRR is frontent-agnostic), but serializers, which raise DRF ValidationError which is then processed by the exception handler which one can override: 
- https://www.django-rest-framework.org/api-guide/exceptions/#validationerror
- https://www.django-rest-framework.org/api-guide/exceptions/#custom-exception-handling

depending on how you setup your exception handler (or use the default), your will need to handle the response body coming from the API endpoint appropriately (this is DRF not DRR so I'm refering you to their official docs)

**Comment by oriyalperin** [comment]
I have one more question,
after logging in, the `last_login` field doesn't update and remains empty. Is this the default behavior?

**Comment by apragacz** [comment]
@oriyalperin I assumed `last_login` is updated by the authenticator, but maybe it's not the case. I need to double-check this.

**Comment by apragacz** [comment]
@oriyalperin ok, so I did a check:

1.  for session-based logins, we're using `auth.login()`:
    https://github.com/apragacz/django-rest-registration/blob/e6421ac9541b683dcb86e8136df39d59c0d5f3b4/rest_registration/api/views/login.py#L103
    which in turn fires `user_logged_in` signal:
    https://github.com/django/django/blob/5e98959d9242c57a55c65847758781f82d386fa4/django/contrib/auth/__init__.py#L152
    which will run connected `update_last_login` handler:
    https://github.com/django/django/blob/9c19aff7c7561e3a82978a272ecdaad40dda5c00/django/contrib/auth/apps.py#L28
    
2. however, for token-based logins, we're not using `auth.login()` for obvious reasons. but we neither fire `user_logged_in` signal, which should be fired in that case. I'm gonna add it.

so the question is - are you using token-based login only? if yes then that should explain it. otherwise, I'm not sure

**Comment by oriyalperin** [comment]
Thanks for the detailed answer!
Yes, I'm using only token-based login.

**Comment by apragacz** [comment]
@oriyalperin the issue with last_login should be addressed via #280 soon. Do you have any other questions?

**Comment by oriyalperin** [comment]
No, thank you!
