### ISSUE TITLE
Default register output serializer should include a token when appropriate

### ISSUE THREAD

**Issue by ckeeney** [apragacz/django-rest-registration#31]
If the client does not get an AuthToken after registration, the user must provide credentials immediately after registering.

I was able to add a token to the default serializer with the following custom serializer, but the token should really be created in the view instead.

```python
from rest_registration.api.serializers import DefaultUserProfileSerializer
from rest_framework import serializers
from rest_framework.authtoken.models import Token


class MyRegistrationSerializer(DefaultUserProfileSerializer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.Meta.fields += ('token',)

    token = serializers.SerializerMethodField()

    def get_token(self, user):
        token = Token.objects.create(user=user)
        return token.key
```

and in `settings.py`:

```python
REST_REGISTRATION = {
# ...
    'REGISTER_OUTPUT_SERIALIZER_CLASS': '...MyRegistrationSerializer',
}
```

**Comment by ckeeney** [comment]
If you want this behavior (users don't have to login after they signup) AND you want to verify registered users, this token must be instead added to the `VerifyRegistrationSerializer`, but there is not currently a setting to create a custom `VerifyRegistrationSerializer`.

**Comment by ckeeney** [comment]
You can replace the default verify registration response, which looks like this:

```python
{ "detail": "User verified successfully"}
```
with a response that includes a token (or anything else you like):
```python
{"token": "2f1ccff8f1154d67b21bbd0665235cb07e4958c2"}
```
with a view similar to this:

```python
from rest_framework import status
from django.http import JsonResponse
from rest_framework.authtoken.models import Token
from rest_registration.api.views import verify_registration as rr_verify_registration


def verify_registration(request):
    r = rr_verify_registration(request)
    if r.status_code == status.HTTP_200_OK:
        (token, _) = Token.objects.get_or_create(user_id=request.POST['user_id'])
        token_response = {'token': token.key}
        return JsonResponse(token_response, status=status.HTTP_200_OK)
    else:
        return r
```

**Comment by ckeeney** [comment]
Thanks for the thorough reply.  After reading your arguments, I agree creating a token in the serializer is not the anti-pattern I thought it was.

> In my opinion, this is very specific use case, too specific to add some configuration option. But for that you have REGISTER_SERIALIZER_CLASS and REGISTER_OUTPUT_SERIALIZER_CLASS, so you can provide your custom serializer.

I think most websites give users an authenticated session immediately after creating an account.  It's obviously possible to override the default views or serializers to accomplish this, but it's surprising that it isn't more built-in to this library.

**Comment by apragacz** [comment]
@ckeeney 

As you mentioned earlier, you can override `REGISTER_OUTPUT_SERIALIZER_CLASS` to return auth token but there is no way to return the auth token or authenticate via session when the user verifies the email after registration:

> > There is not currently a setting to create a custom VerifyRegistrationSerializer.
>
> This is actually quite interesting idea. Currently the only way to control this output is to use different function in SUCCESS_RESPONSE_BUILDER. I'm still not convinced, but I will think about this. You are welcome to provide more convincing arguments, of course :)

But in the meantime issue #40 has been created and resolved, which addresses this problem. I'm just mentioning that in case you or someone else stumbling upon this issue wants to know whether this problem was solved or not.
