### ISSUE TITLE
Doesn't seem to be a way to handle expired registration verifications.

### ISSUE THREAD

**Issue by akoumjian** [apragacz/django-rest-registration#34]
Using the default settings, there doesn't seem to be a way for a user to recover from an initial expired verification link. To reproduce:

1. Register a user by email address
2. Wait for `REGISTER_VERIFICATION_PERIOD` to end
3. Use signature & timestamp to try to verify.

The signature has expired, as expected. From here, the user should either be able to re-register or to use the `send-password-reset-link` in order to complete verificaiton. If they try to register, they will get a "User with this email already exists" error, and if they try to reset the password they will get a "User not found" error. 

My suggested fix would be to pass the `required_verify=False` option to the `get_user_by_lookup_dict` method here: https://github.com/apragacz/django-rest-registration/blob/master/rest_registration/api/views/reset_password.py#L73

**Comment by apragacz** [comment]
I agree.
The only thing I have against that is that currently we are using `is_active` user attribute whether someone is verified or not. In case site admin uses the same atribute to block users, the user could unblock himself with reset password option. That problem could be avoided by introducing additional setting for the user attribute name which may be different than `USER_VERIFICATION_FLAG_FIELD`.

**Comment by apragacz** [comment]
The fix will be released in next version (`0.4.0`).

**Comment by akoumjian** [comment]
Thanks @apragacz !
