### ISSUE TITLE
Change parameters in confirm-email/confirm-user.

### ISSUE THREAD

**Issue by amorino** [apragacz/django-rest-registration#39]
Right now we can change the frontend URL in settings to create a link like this: 

`http://front-host/confirm-email/?user_id=4&timestamp=1553208302&signature=0uK-akKnv9kSHNlPI1BDhT8Ddsbc`.

Is it possible to change the parameters to something like this?:

 `http://front-host/confirm-email/4/1553208302/0uK-akKnv9dkSHNlPI1BDhT8Dsbc`

**Comment by apragacz** [comment]
Currently, there is no way to do that.
My proposal would be to add `VERIFICATION_URL_BUILDER` which would be able to replace the logic of `URLParamsSigner.get_url()` by a custom function. the bulider function would receive the signer object and construct the url using `signer.get_base_url()` and `signer.get_signed_data()`.

The builder function should be able to support many types of signer. In other words, considering your example, it would be solely up to the implementer of this builder function to map specific values like `user_id`, `email`, `timestamp`, `signature` in correct positions and encode them properly in the URL.

What do you think about that?

**Comment by apragacz** [comment]
@amorino Do you have any further comments? I already provided some implementation for the potential solution (described above) of the problem. If you have nothing against it, I will add some tests and merge it.

**Comment by apragacz** [comment]
This change will be introduced in next version (`0.4.2`).
