### ISSUE TITLE
Allow users to be automatically logged in upon verifying a their registration

### ISSUE THREAD

**Issue by gcbirzan** [apragacz/django-rest-registration#40]
Currently, the user has to log in with his credentials, but this is pointless from a security point of view, since if he has access to the email he could reset the password.

There should be an option to automatically log in users after they verify their account.

**Comment by apragacz** [comment]
Yes, you can do that, but these endpoints serve entirely different functionality: one is used for authentication, the other to restore the possibility to authenticate via password, as this is the method preferred currently by Django REST Registration.

I would agree that it could be useful not from the security standpoint, but from the functionality standpoint - the user does not need to re-enter the password when he/she confirms his/her e-mail after registration. So as opt-in option it would be certainly useful.

**Comment by gcbirzan** [comment]
I didn't mean log in via an endpoint, I might misunderstand what you're trying to say there. My point was simply that verifying your registration should be enough to log you, just as resetting your password should.

I'll try to get some time this weekend to make a PR, but, most likely, it'll be some time Monday.

**Comment by apragacz** [comment]
This feature was released in version `0.4.2`.
