### ISSUE TITLE
Verification via Signature

### ISSUE THREAD

**Issue by Umarhayat3** [apragacz/django-rest-registration#42]
Dear Community members,
I am new to Django and do not know anything about "verification via signature". My question is where can I find the signature in postman and how? so that I can use it for registration-verification.
Thanks,
![Screenshot from 2019-04-09 13-16-21](https://user-images.githubusercontent.com/46805741/55784340-c9ad1280-5ac9-11e9-88df-88c46cf56891.png)

**Comment by apragacz** [comment]
@Umarhayat3 
The signature is generated automatically by the register endpoint as a part of verification url (user needs to click on it to verify his/her account) in the verification e-mail sent to the user. There is more verbose explanation here:
https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/register.html#verification-workflow

**Comment by apragacz** [comment]
@Umarhayat3 If you don't have any further question then I will close this issue within few days.
