### ISSUE TITLE
Customize email registration

### ISSUE THREAD

**Issue by valerymelou** [apragacz/django-rest-registration#45]
Is it possible to customize the email registration? Especially add some more validation on the new email. I want to check if the email is already used by another user before allowing it to be set as the email address of the user.
I already overrode the serializer used in the registration process to enforce unique email addresses and I would like to know if we can have the same for the register email.

**Comment by apragacz** [comment]
Currently it is not possible. Probably the only way is to make `RegisterEmailSerializer` to be a pluggable, similarly like we did in the `login` view, which uses `'LOGIN_SERIALIZER_CLASS'` setting key to get the serializer (by default it is `rest_registration.api.serializers.DefaultLoginSerializer`).

**Comment by apragacz** [comment]
This improvement will be released in the next version (`0.4.4`)
