### ISSUE TITLE
How to report vulnerabilities

### ISSUE THREAD

**Issue by peterthomassen** [apragacz/django-rest-registration#62]
It would be nice if you added some information to the README how you expect vulnerabilities to be reported. (I'd like to report one.)

**Comment by apragacz** [comment]
Well, there is no established routine for reporting serious security vulnerabilities (the ones you should not publish on the issues page). If you think this one is a serious one then please send a message to my public e-mail: apragacz@o2.pl. If not, then create an issue as usual.

I think I will create a separate CONTRIBUTING.md file for this kind of information, like I mentioned in issue #59.

**Comment by peterthomassen** [comment]
for reference: https://github.com/apragacz/django-rest-registration/commit/26d094fab65ea8c2694fdfb6a3ab95a7808b62d5

**Comment by apragacz** [comment]
Closing as it should be done in issue #64.
