### ISSUE TITLE
Add extra context to template rendering

### ISSUE THREAD

**Issue by joshvillbrandt** [apragacz/django-rest-registration#68]
Hi! Is there a way to pass extra context variables to the template rendering? This appears hard-coded after finding the rendering [in the source](https://github.com/apragacz/django-rest-registration/blob/63083bbecbe0311a1c4e823979c6cd039ffcc819/rest_registration/notifications/email.py#L36).

Maybe a callable function defined in the settings could help generate a supplemental context. Specifically, I'm looking to pass in the front-end base URL for a logo image in the html templates.

Thanks!

**Comment by apragacz** [comment]
@joshvillbrandt 
I added `‘VERIFICATION_TEMPLATE_CONTEXT_BUILDER’` settings key so the template context can be customized. The signature of the function looks as follows:

```python
def build_default_template_context(
        user, user_address, data,
        notification_type=None, notification_method=None):
    ...
```
There is also more verbose description in the docs which you can find here:

https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/global_verification.html#verification-template-context-builder

This feature should be released in next version (`0.5.2`).
