### ISSUE TITLE
User creation during registration should be atomic

### ISSUE THREAD

**Issue by apragacz** [apragacz/django-rest-registration#79]
In other words, if the verification e-mail cannot be sent, the user should not be created, to avoid 'zombie' users which cannot be used because the e-mail setup is misconfigured.

This issue was created from issue #78.

**Comment by bradbeattie** [comment]
If the app created its own table to store registration status, it could tell the difference between a zombie account and a regular account that's been deactivated intentionally. Alternatively, catching the email failure and deleting the user account would do, yeah?

**Comment by apragacz** [comment]
> If the app created its own table to store registration status, it could tell the difference between a zombie account and a regular account that's been deactivated intentionally.

Django-REST-registration was intentionally made modeless, So we intentionally don't thold any registration profiles or something like that. But thanks for the idea.

> Alternatively, catching the email failure and deleting the user account would do, yeah?

We could do that, but I think using `transaction.atomic` decorator / context manager when performing both operations (creating user, sending verification e-mail) would make more sense. I need to add a test for it to confirm that this works.

Thanks for your feedback!
