### ISSUE TITLE
Extend views

### ISSUE THREAD

**Issue by itzmanish** [apragacz/django-rest-registration#89]
Is there any way to extend rest registration views and adding other functionallity?

**Comment by itzmanish** [comment]
In DRR all views are function based so i don't know how i can extend it. Also to add simplejwt i need to modify login views. So It will be nice for everyone if DRR have generic views.

**Comment by apragacz** [comment]
Hi @itzmanish ,
There is an issue #55 where is already a discussion going on about turning the function views into class based views. So I would route all related discussion there:

Therefore I'm closing this one as duplicate of  #55 .

BTW: I'm planning to address issue #84 in few days.
