### ISSUE TITLE
Phone_number and OTP authentication

### ISSUE THREAD

**Issue by vikasgirdhar30** [apragacz/django-rest-registration#93]
Can we use Mobile_Number or username instead of username in Login API ?

**Comment by apragacz** [comment]
Hi @vikasgirdhar30,
yes, you can do that.

You can set either `LOGIN_FIELDS` property in your user model or `'USER_LOGIN_FIELDS'` key in `REST_REGISTRATION` settings dict.

In other words let's assume that the mentioned phone field is named `mobile_number`.
You either need to set this in your user model:

```python
class MyUser(AbstractBaseUser):
    LOGIN_FIELDS = ['username', 'mobile_number']
    # ...
```

or need to set this in your `settings.py`:

```python
REST_REGISTRATION = {
    # ...

    'USER_LOGIN_FIELDS': ['username', 'mobile_number'],

    # ...
}
```

I prefer the former solution (setting the fields directly in the custom user model, if it is defined).

See this documentation page for details:
https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/user.html#user-login-fields

(this is not documented well currently, unfortunately).

**Comment by vikasgirdhar30** [comment]
Can we remove 'confirm password' field from register API and add 'mobile
number' field.

**Comment by apragacz** [comment]
Hi @vikasgirdhar30,
I'd highly recommend you to check the existing docs.

https://django-rest-registration.readthedocs.io/

> Can we remove 'confirm password' field from register API ...

Removing the `password_confirm` field is described here:
https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/register.html#register-serializer-password-confirm

> ... and add 'mobile number' field.

If you add this field to your custom user model, it will be exposed as a field in the registration api by default, see:
https://django-rest-registration.readthedocs.io/en/latest/detailed_configuration/register.html#defaultregisteruserserializer

I think this should be perhaps better described as the current description is lakonic.

**Comment by vikasgirdhar30** [comment]
Hi Apragacz,

I am trying to mobile_number field as well in Signup API. Could you please
confirm where i need to make changes?

**Comment by apragacz** [comment]
Hi @vikasgirdhar30 ,

You need to add `mobile_number` field to your custom Django user model. I already said that in previous comment:

> If you add this field to your custom user model, it will be exposed as a field in the registration api by default, see: ...

If you don't know how to set up a custom user model, see the Django docs here:

https://docs.djangoproject.com/en/2.2/topics/auth/customizing/#substituting-a-custom-user-model

This is Django specific question, not Django-REST-Registration specific one; therefore you should seek help on the `django-users` mailing list or `#django` IRC channel, as described here:
https://docs.djangoproject.com/en/2.2/faq/help/#how-do-i-do-x-why-doesn-t-y-work-where-can-i-go-to-get-help
